/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.33.0
 * Product:       sht3x
 * Model-Version: 1.0.0
 */
/*
 * Copyright (c) 2023, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSht3x.h>
#include <Wire.h>

SensirionI2cSht3x sensor;

static char errorMessage[64];
static int16_t error;

bool enableHeater = false;
uint8_t loopCnt = 0;
uint16_t aStatusRegister = 0u;

static inline bool test_flag(uint16_t state, uint16_t flag)
{
  return (state & flag) != 0;
}

enum
{
  WRITE_DATA_CHECKSUM_STATUS = 1u << 0,
  COMMAND_STATUS = 1u << 1,
  SYSTEM_RESET_DETECTED = 1u << 4,
  TEMP_ALERT_EN = 1u << 10,
  HUM_ALERT_EN = 1u << 11,
  HEATER_EN = 1u << 13,
  ALERT_PENDING = 1u << 15,
};

void setup()
{
  Serial.begin(115200);
  while (!Serial)
  {
    delay(100);
  }
  // Priority 2 (P2) : GPIO pins can be freely used without restrictions.
  // GPIO5 and GPIO6 are P2
  // GPIO5 = SCL, GPIO6 = SDA
  // bool setPins(int sdaPin, int sclPin);
  Wire.setPins(6, 5);
  Wire.begin();
  sensor.begin(Wire, SHT30_I2C_ADDR_44);

  sensor.stopMeasurement();
  delay(1);
  sensor.softReset();
  delay(100);
  error = sensor.readStatusRegister(aStatusRegister);
  if (error != NO_ERROR)
  {
    Serial.print("Error trying to execute readStatusRegister(): ");
    errorToString(error, errorMessage, sizeof errorMessage);
    Serial.println(errorMessage);
    return;
  }
  Serial.print("aStatusRegister: ");
  Serial.print(aStatusRegister, 2);
  Serial.println();

  Serial.print("Heater Enabled State: ");
  if (test_flag(aStatusRegister, HEATER_EN))
    Serial.println("ENABLED");
  else
    Serial.println("DISABLED");
}

void loop()
{
  float aTemperature = 0.0;
  float aHumidity = 0.0;
  error = sensor.measureSingleShot(REPEATABILITY_MEDIUM, false, aTemperature, aHumidity);
  if (error != NO_ERROR)
  {
    Serial.print("Error trying to execute measureSingleShot(): ");
    errorToString(error, errorMessage, sizeof errorMessage);
    Serial.println(errorMessage);
    return;
  }
  Serial.print("aTemperature: ");
  Serial.print(aTemperature);
  Serial.print("\t");
  Serial.print("aHumidity: ");
  Serial.print(aHumidity);
  Serial.println();

  delay(1000);

  // Toggle heater enabled state every 30 seconds
  // An ~3.0 degC temperature increase can be noted when heater is enabled
  if (loopCnt >= 30)
  {
    enableHeater = !enableHeater;
    enableHeater ? sensor.enableHeater() : sensor.disableHeater();
    error = sensor.readStatusRegister(aStatusRegister);
    if (error != NO_ERROR)
    {
      Serial.print("Error trying to execute readStatusRegister(): ");
      errorToString(error, errorMessage, sizeof errorMessage);
      Serial.println(errorMessage);
      return;
    }
    Serial.print("aStatusRegister: ");
    Serial.print(aStatusRegister, 2);
    Serial.println();

    Serial.print("Heater Enabled State: ");
    if (test_flag(aStatusRegister, HEATER_EN))
      Serial.println("ENABLED");
    else
      Serial.println("DISABLED");

    loopCnt = 0;
  }
  loopCnt++;
}
